[build]
  command = "npm ci --production=false && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 