[build]
  base = "app"
  command = "npm ci && npm run build"
  publish = "app/.next"

[build.environment]
  NODE_VERSION = "18"

# Next.js plugin for better compatibility
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 