[build]
  command = "echo 'Using pre-built files' && ls -la .next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 